spring:
  application:
    name: kr.co.cms


  devtools:
    restart:
      enabled: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

# Database 설정
  datasource:
    url: jdbc:mysql://210.178.108.186:53306/myerp
    username: sin
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발시에는 update, 운영시에는 validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

#  data:
#    mongodb:
#      uri: mongodb+srv://cms:OG1vWxXDq0XFdEM1@cms-3jo.zxpmb5d.mongodb.net/?retryWrites=true&w=majority&appName=cms-3jo

logging:
  level:
    org.springframework.boot.autoconfigure: WARN

server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      force: true
      force-response: true
      enabled: true